name: Go Build and Publish

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.21]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [amd64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Lint
      run: go fmt ./... && go vet ./...

    - name: Get Git tag
      run: |
        TAG=$(git describe --tags)
        echo "Git tag is $TAG"
        echo "::set-output name=tag::$TAG"

    - name: Build for ${{ matrix.os }}/${{ matrix.arch }}
      run: |
        TAG=$(echo $TAG | cut -d'-' -f 1)
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myapp_${{ matrix.os }}_${{ matrix.arch }}_${TAG} .

    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: myapp_${TAG}
        path: myapp_*
